apiVersion: v1
data:
  BORG_REPO: /backup
kind: ConfigMap
metadata:
  labels:
    app: borg-backup
  name: borg-backup-config
  namespace: default
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: borg-backup
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 100
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: borg-backup
            image: localhost:32000/borg-backup:1.0.0
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: borg-backup-config
            - secretRef:
                name: borg-backup-secrets
            volumeMounts:
            - name: backup
              mountPath: /backup
            - name: backup-data
              mountPath: /backup-source/data/
            - name: backup-etc
              mountPath: /backup-source/etc/
            - name: backup-home
              mountPath: /backup-source/home/
            - name: backup-root
              mountPath: /backup-source/root/
            - name: backup-usr
              mountPath: /backup-source/usr/
            - name: backup-var
              mountPath: /backup-source/var/
          restartPolicy: Never
          volumes:
          - name: backup
            hostPath:
              path: /mnt/backup
              type: DirectoryOrCreate
          - name: backup-data
            hostPath:
              path: /data
              type: DirectoryOrCreate
          - name: backup-etc
            hostPath:
              path: /etc
              type: DirectoryOrCreate
          - name: backup-home
            hostPath:
              path: /home
              type: DirectoryOrCreate
          - name: backup-root
            hostPath:
              path: /root
              type: DirectoryOrCreate
          - name: backup-usr
            hostPath:
              path: /usr
              type: DirectoryOrCreate
          - name: backup-var
            hostPath:
              path: /var
              type: DirectoryOrCreate
